#!/usr/bin/env sh

set -e

echo 'Cloning build repository'

git clone https://github.com/sftrabbit/joseph-mansfield-build.git build
cd build

echo 'Configuring git'

git config user.name "GitHub Actions"

echo 'Creating build commit'

rm -r *
cp -r ../_site/* .
cp ../README.build.md ./README.md
echo "josephmansfield.uk" > CNAME

git add -A
timestamp="$(date +"%Y%m%d%H%M%S")"
git commit -m "Build $timestamp"

echo 'Pushing build commit'

git push "git@github.com:sftrabbit/joseph-mansfield-build.git" master
